# Generated by Django 3.2 on 2023-03-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleModel',
            new_name='Sample',
        ),
    ]
